import * as Tone from "tone";

// ============================================================
// Pre-rendered voice clips (ElevenLabs, generated by scripts/prerender-voices.mjs).
// Loads /voices/manifest.json at startup; if absent, hasClip() is always false
// and the game uses on-device Web Speech (voice.js) instead. Clips play through
// the Tone audio clock so the mentor's voice can land on the bar.
// ============================================================

let manifest = null;
const players = new Map(); // key -> Tone.Player

export function voiceSlug(mentor) {
  return String(mentor).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export async function initClips() {
  try {
    const r = await fetch("/voices/manifest.json", { cache: "no-cache" });
    if (r.ok) manifest = await r.json();
  } catch (e) { manifest = null; }
  return !!manifest;
}

export function hasManifest() { return !!manifest; }
export function hasClip(key) { return !!(manifest && manifest[key]); }

// Kick off loading for a set of keys (idempotent).
export function preload(keys) {
  if (!manifest) return;
  keys.forEach((key) => {
    if (!manifest[key] || players.has(key)) return;
    try {
      const pl = new Tone.Player({ url: manifest[key], onerror: () => {} }).toDestination();
      pl.volume.value = -1;
      players.set(key, pl);
    } catch (e) {}
  });
}

// Play a clip (optionally at a precise audio time). Returns false if it's not
// loaded/ready yet, so the caller can fall back to Web Speech.
export function playClip(key, time) {
  const pl = players.get(key);
  if (!pl || !pl.loaded) return false;
  try {
    if (time != null) pl.start(time); else pl.start();
    return true;
  } catch (e) { return false; }
}
